#!/bin/bash

fastQCDir=Software/FastQC
trimmomaticJar=Software/trimmomatic-0.20/dist/jar/trimmomatic-0.20.jar
cutadaptFile=Software/cutadapt-1.0/cutadapt
solexaQADir=Software/SolexaQA

samToolsDir=Software/samtools-0.1.18
bwaDir=Software/bwa-0.6.2
tophatDir=Software/tophat-2.0.6.Linux_x86_64
cufflinksDir=Software/cufflinks-2.0.2.Linux_x86_64
mapspliceDir=Software/MapSplice_multi_threads_2.0.1.9/bin
rsemDir=Software/rsem-1.2.3
star=Software/STAR_2.2.0c.Linux_x86_64
picardDir=Software/picard-tools-1.81
ubu=Software/ubu-1.2-jar-with-dependencies.jar
useqDir=Software/USeq_8.5.1/Apps

gtfFile=/data/Genomes/iGenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf
genomeIndexPath=/data/Genomes/iGenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/Bowtie2Index/genome
genomeChromosomesDir=/data/Genomes/iGenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/Chromosomes
genomeFastaFile=/data/Genomes/iGenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa
