#!/bin/bash

currentDir=`pwd`
dataDir=compute/BodyMap
summDir=summarization/BodyMap
genomeDir=Genomes/hg19
genomeFile=$genomeDir/hg19.fa
ucscCanonicalFile=library/UCSC_hg19_knownCanonical.txt
ucscCanonicalMetaFile=library/UCSC_hg19_knownCanonical_Meta.txt
ucscCanonicalNoSexChromMetaFile=library/UCSC_hg19_knownCanonical_Meta_NoSexChrom.txt
ensemblMetaFile=library/Ensembl_CRCh37_Gene_Meta.txt
ensemblSymbolMetaFile=library/Ensembl_CRCh37_GeneSymbol_Meta.txt

mkdir -p $dataDir $summDir

source scripts/rnaseq/paths
source scripts/create_temp_files

#tail -n +2 $ucscCanonicalFile > $tmpFile1
#python2 code/SelectColumns.py $tmpFile1 4,0,1,2 $tmpFile2
#python2 code/AddLengthGCToMeta.py $tmpFile2 ~/genomes/hg19 $ucscCanonicalMetaFile
#python2 code/FilterFile.py $ucscCanonicalMetaFile "x[1] not in ['chrX', 'chrY']" 0 $ucscCanonicalNoSexChromMetaFile

##$bwaDir/bwa index -p $bwaDir/indices/hg19 $genomeFile
##$samToolsDir/samtools faidx $genomeFile

#seq 872 887 | parallel --max-procs 16 scripts/rnaseq/process_tophat_from_sra http://ftp-private.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/ERR/ERR030/ERR030{}/ERR030{}.sra $dataDir "'--num-threads 16 --no-coverage-search --mate-inner-dist 110'" "''"
#seq 888 903 | parallel --max-procs 16 scripts/rnaseq/process_tophat_from_sra http://ftp-private.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/ERR/ERR030/ERR030{}/ERR030{}.sra $dataDir "'--num-threads 16 --no-coverage-search'" "''"

#for f in $dataDir/*.bam
#do
#  $samToolsDir/samtools view -c -F 4 $f > ${f/\.tophat\.bam/.depth} &
#done
#wait

#seq 872 903 | parallel --max-procs 16 scripts/rnaseq/htseq_gene_count $dataDir/ERR030{}.tophat.bam no $dataDir/ERR030{}.tophat.geneCounts
#seq 872 903 | parallel --max-procs 16 scripts/rnaseq/pileup_count $dataDir/ERR030{}.tophat.bam $genomeFastaFile $ucscCanonicalNoSexChromMetaFile $dataDir/ERR030{}.tophat.pileupCounts

##  scripts/rnaseq/find_gene_counts $dataDir $id ATCTCGTATGCCGTCTTCTGCTTG $genomeFile $ucscCanonicalNoSexChromMetaFile $id.geneCounts
##  qsub scripts/rnaseq/find_gene_counts -l nodes=1:ppn=1,pmem=4gb,walltime=4:00:00 -N find_gene_counts -q batch -v dataDir=$dataDir,id=$id,adapterSequence=ATCTCGTATGCCGTCTTCTGCTTG,genomeFile=$genomeFile,metaFile=$ucscCanonicalNoSexChromMetaFile,outFile=$id.geneCounts

function copySummFiles {
  suffix=$1
  aligner=$2

  cp -v $dataDir/ERR030872${suffix} $summDir/Thyroid_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030873${suffix} $summDir/Testes_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030874${suffix} $summDir/Ovary_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030875${suffix} $summDir/WBC_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030876${suffix} $summDir/Skeletal_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030877${suffix} $summDir/Prostate_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030878${suffix} $summDir/Lymph_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030879${suffix} $summDir/Lung_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030880${suffix} $summDir/Adipose_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030881${suffix} $summDir/Adrenal_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030882${suffix} $summDir/Brain_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030883${suffix} $summDir/Breast_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030884${suffix} $summDir/Colon_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030885${suffix} $summDir/Kidney_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030886${suffix} $summDir/Heart_BodyMap_A.$aligner.readsraw.txt
  cp -v $dataDir/ERR030887${suffix} $summDir/Liver_BodyMap_A.$aligner.readsraw.txt

  cp -v $dataDir/ERR030888${suffix} $summDir/Adipose_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030889${suffix} $summDir/Adrenal_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030890${suffix} $summDir/Brain_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030891${suffix} $summDir/Breast_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030892${suffix} $summDir/Colon_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030893${suffix} $summDir/Kidney_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030894${suffix} $summDir/Heart_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030895${suffix} $summDir/Liver_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030896${suffix} $summDir/Lung_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030897${suffix} $summDir/Lymph_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030898${suffix} $summDir/Prostate_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030899${suffix} $summDir/Skeletal_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030900${suffix} $summDir/WBC_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030901${suffix} $summDir/Ovary_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030902${suffix} $summDir/Testes_BodyMap_B.$aligner.readsraw.txt
  cp -v $dataDir/ERR030903${suffix} $summDir/Thyroid_BodyMap_B.$aligner.readsraw.txt
}

#rm -fv $summDir/*
#copySummFiles .gene gnumap
#copySummFiles .tophat.geneCounts tophatgene
#copySummFiles .tophat.pileupCounts tophatpileup

#for f in $summDir/*tophatgene*readsraw.txt
#do
#  echo Converting to gene symbols for $f
#  python code/MergeMatrixOnRowNames.py $f library/Ensembl_GRCh37.p10_GeneSymbols.txt $tmpFile1 False
#  python code/FilterFile.py $tmpFile1 "len(x) > 2" 0 $tmpFile2
#  python code/SelectColumns.py $tmpFile2 2,1 $tmpFile1
#  python code/SummarizeDuplicateRowValues.py $tmpFile1 sum $f
#done

#for x in gnumap tophatgene tophatpileup
#do
#  cp -v $dataDir/ERR030872.depth $summDir/Thyroid_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030873.depth $summDir/Testes_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030874.depth $summDir/Ovary_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030875.depth $summDir/WBC_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030876.depth $summDir/Skeletal_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030877.depth $summDir/Prostate_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030878.depth $summDir/Lymph_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030879.depth $summDir/Lung_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030880.depth $summDir/Adipose_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030881.depth $summDir/Adrenal_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030882.depth $summDir/Brain_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030883.depth $summDir/Breast_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030884.depth $summDir/Colon_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030885.depth $summDir/Kidney_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030886.depth $summDir/Heart_BodyMap_A.$x.depth.txt
#  cp -v $dataDir/ERR030887.depth $summDir/Liver_BodyMap_A.$x.depth.txt
#
#  cp -v $dataDir/ERR030888.depth $summDir/Adipose_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030889.depth $summDir/Adrenal_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030890.depth $summDir/Brain_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030891.depth $summDir/Breast_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030892.depth $summDir/Colon_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030893.depth $summDir/Kidney_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030894.depth $summDir/Heart_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030895.depth $summDir/Liver_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030896.depth $summDir/Lung_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030897.depth $summDir/Lymph_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030898.depth $summDir/Prostate_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030899.depth $summDir/Skeletal_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030900.depth $summDir/WBC_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030901.depth $summDir/Ovary_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030902.depth $summDir/Testes_BodyMap_B.$x.depth.txt
#  cp -v $dataDir/ERR030903.depth $summDir/Thyroid_BodyMap_B.$x.depth.txt
#done

function matricize {
  aligner=$1
  metaFile=$2

  for letter in A B
  do
    scripts/transformRnaSeqSummarized "$summDir/*_${letter}.${aligner}*" $metaFile 0.001 0.001 0.01 matrices/BodyMap.$letter.$aligner.cqn2.txt

    for dataType in readsraw rpkm rpkm2 probnn probln probnb
    do
      scripts/buildMatrix "$summDir/*_${letter}.$aligner.$dataType.txt" matrices/BodyMap.$letter.$aligner.$dataType.txt
      python2 code/ReplaceText.py matrices/BodyMap.$letter.$aligner.$dataType.txt .$dataType.txt "" matrices/BodyMap.$letter.$aligner.$dataType.txt
    done

    Rscript --vanilla code/CalculateCqn.R matrices/BodyMap.$letter.$aligner.readsraw.txt $metaFile matrices/BodyMap.$letter.$aligner.cqn.txt
    python2 code/ReplaceText.py matrices/BodyMap.$letter.$aligner.cqn.txt .readsraw.txt "" matrices/BodyMap.$letter.$aligner.cqn.txt
    python2 code/ReplaceText.py matrices/BodyMap.$letter.$aligner.cqn2.txt .readsraw.txt "" matrices/BodyMap.$letter.$aligner.cqn2.txt
  done
}

#matricize gnumap $ucscCanonicalNoSexChromMetaFile
#matricize tophatgene $ensemblSymbolMetaFile
#matricize tophatpileup $ucscCanonicalNoSexChromMetaFile

function buildPredictDataFile {
  dataFile1=$1
  dataFile2=$2
  dataFile3=$3
  aligner=$4
  outFile=$5

  python2 code/MergeMatrixOnRowNames.py $dataFile1 $dataFile2 $tmpFile1
  python2 code/MergeMatrixOnRowNames.py $tmpFile1 $dataFile3 $tmpFile2
  head -1 $tmpFile2 > $tmpFile3
  python2 code/ReplaceText.py $tmpFile3 _BodyMap_A.${aligner} "" $tmpFile4
  python2 code/ReplaceText.py $tmpFile4 _BodyMap_B.${aligner} "" $tmpFile4
  python2 code/ReplaceText.py $tmpFile4 _Wang.${aligner} "" $tmpFile4
  python2 code/ReplaceText.py $tmpFile4 Brain2 Brain $tmpFile4
  ##python2 code/ReplaceText.py $tmpFile4 BT474 Breast $tmpFile4
  ##python2 code/ReplaceText.py $tmpFile4 HME Breast $tmpFile4
  ##python2 code/ReplaceText.py $tmpFile4 MCF7 Breast $tmpFile4
  ##python2 code/ReplaceText.py $tmpFile4 T47D Breast $tmpFile4
  python2 code/InsertColumnViaExpression.py $tmpFile4 "'Class'" $tmpFile3
  python2 code/SelectColumns.py $tmpFile3 49,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48 $tmpFile4
  cat $tmpFile2 $tmpFile4 > $tmpFile3
  python2 code/SelectColumns.py $tmpFile3 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,38,39,41,42,45,47 $tmpFile4
  python2 code/ReplaceText.py $tmpFile4 ".${aligner}" "" $outFile
}

mlflexDir=`pwd`/compute/ML-Flex-UPC

function buildMlFlexFiles {
  aligner=$1
  dataType=$2
  template=$3

  dataFile1=matrices/BodyMap.A.$aligner.$dataType.txt
  dataFile2=matrices/BodyMap.B.$aligner.$dataType.txt
  dataFile3=matrices/Wang.$aligner.$dataType.txt
  dataFile=$mlflexDir/InputData/$aligner.$dataType.txt
  buildPredictDataFile $dataFile1 $dataFile2 $dataFile3 $aligner $dataFile

  expFile=$mlflexDir/Experiments/${template}_${aligner}_${dataType}
  runFile=$mlflexDir/run_${template}_${aligner}_${dataType}

  python2 code/ReplaceText.py $mlflexDir/Experiments/${template} "%%inputFile%%" "$dataFile" $expFile
  python2 code/ReplaceText.py $mlflexDir/run "%%experimentFile%%" "$expFile" $runFile
  chmod 777 $runFile
}

#rm -fv $mlflexDir/run_*

#for x in gnumap tophatgene tophatpileup
#do
#  for dataType in cqn cqn2 rpkm2 probnn probln probnb
#  do
#    echo Building ML-Flex files for $x and $dataType
#    buildMlFlexFiles $x $dataType BodyMap_TrainTest
#  done
#done

#currentDir=`pwd`
#cd $mlflexDir
#for runFile in run_BodyMap_TrainTest_*
#do
#  ./$runFile
#done
#cd $currentDir

#for dataType in rpkm rpkm2 cqn cqn2 probnn probln probnb
#do
#  mFile=matrices/BodyMap.A.gnumap.$dataType.txt
#  outFile=matrices/BodyMap.A.gnumapsymbol.$dataType.txt
#
#  python2 code/SelectColumns.py $ucscCanonicalFile 4,5 $tmpFile1
#  python2 code/MergeMatrixOnRowNames.py $tmpFile1 $mFile $tmpFile2 True
#  python2 code/SelectColumns.py $tmpFile2 1tolast $tmpFile3
#  python2 code/AverageDuplicateRowValues.py $tmpFile3 $outFile True
#done

source scripts/delete_temp_files
