#!/bin/bash

dataDir=compute/MAQC
taqmanReferenceFile=library/GPL4097.txt
taqmanMapFile=library/GPL4097_TaqMan_Gene.txt
geneFile18=library/UCSC_hg18_genes.txt
geneSymbolMetaFile18=library/UCSC_hg18_genes_Meta.txt

exonsMetaFile19=library/Ensembl_GRCh37_Exon_Meta.txt
geneMetaFile19=library/Ensembl_CRCh37_Gene_Meta.txt
geneSymbolMetaFile19=library/Ensembl_CRCh37_GeneSymbol_Meta.txt

source scripts/create_temp_files
source scripts/rnaseq/paths

########################################
# Parse meta files
########################################

#python2 code/SelectColumns.py $taqmanReferenceFile 0,1 $taqmanMapFile

#tail -n +2 $geneFile18 > $tmpFile1
#python2 code/SelectColumns.py $tmpFile1 5,1,3,4 $tmpFile2
#python2 code/FindConsensusGenomicRegions.py $tmpFile2 2 3 $tmpFile1
#python2 code/AddLengthGCToMeta.py $tmpFile1 ~/genomes/hg18 $geneSymbolMetaFile18

#python2 code/ParseGenesFromGtf.py $gtfFile $tmpFile1
#python2 code/AddLengthGCToMeta.py $tmpFile1 $genomeChromosomesDir $geneMetaFile19

#tail -n +2 library/Ensembl_GRCh37.p10_GeneSymbols.txt > $tmpFile1
#python2 code/MergeMatrixOnRowNames.py $geneMetaFile19 $tmpFile1 $tmpFile2 FALSE
#python2 code/FilterFile.py $tmpFile2 "len(x) > 6" 0 $tmpFile1
#python2 code/SelectColumns.py $tmpFile1 -1,1,2,3,4,5 $tmpFile2
#python2 code/CollapseMetaFile.py $tmpFile2 $geneSymbolMetaFile19

########################################
# Parse TAQ data
########################################

function parseTaq {
  tissue=$1
  colIndex=$2
  summarizeFunction=$3
  dataType=$4

  for i in 1 2 3 4
  do
    python2 code/SelectColumns.py misc/MAQC_TAQ_${tissue}${i}_Raw.txt 0,${colIndex} $tmpFile1
    python2 code/InnerJoin.py $taqmanMapFile $tmpFile1 0 0 $tmpFile2 True
    python2 code/SelectColumns.py $tmpFile2 1,2 $tmpFile1
    python2 code/SummarizeDuplicateRowValues.py $tmpFile1 $summarizeFunction tmp${i}
  done

  scripts/buildMatrix "tmp1 tmp2 tmp3 tmp4" $tmpFile1
  tail -n +2 $tmpFile1 > $tmpFile2
  python2 code/TransformMatrixRows.py $tmpFile2 False $summarizeFunction matrices/MAQC_${tissue}.$dataType.txt
  rm tmp1 tmp2 tmp3 tmp4
}

#parseTaq Brain 1 median taqc
#parseTaq Brain 2 majority taqd
###parseTaq UHR 1 median taqc
###parseTaq UHR 2 majority taqd

########################################
# Align RNA-Seq
########################################

m=10
j=5
k=3
a=0.8
#for id in SRR015286 SRR015287 SRR015288 SRR015289
#do
#  qsub ~/RnaSeq/scripts/gnumap_single.script -v fastQFile=compute/MAQC/$id.fastq,genomeFastaFile=Genomes/hg18/hg18.fa,outPath=compute/MAQC/Output/${id}_${m}_${j}_${k}_${a},m=$m,j=$j,k=$k,a=$a
#done

#seq 86 89 | parallel --max-procs 4 -v scripts/rnaseq/process_tophat_from_sra ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR015/SRR0152{}/SRR0152{}.sra $dataDir "'--num-threads 16 --no-coverage-search'" "''"

#for f in $dataDir/*.bam
#do
#  $samToolsDir/samtools view -c -F 4 $f > ${f/\.tophat\.bam/.depth}
#done

########################################
# Map RNA-Seq
########################################

#for id in SRR015286 SRR015287 SRR015288 SRR015289
#do
#  scripts/map_sgr compute/MAQC/Output $id "${id}_10_5_3_0.8_*.sgr" $geneSymbolMetaFile18 8 gene.mapped
#  qsub scripts/map_sgr -l nodes=1:ppn=1,pmem=4gb,walltime=2:00:00 -N map_sgr -q batch -v sgrDir=compute/MAQC/Output,sampleID=$id,inFilePattern="${id}_10_5_3_0.8_*.sgr",metaFile=$geneSymbolMetaFile18,sgrSegmentSize=8,outFileSuffix=gene.mapped
#done

#for id in SRR015286 SRR015287 SRR015288 SRR015289
#do
#  rm compute/MAQC/Output/${id}.sgr
#done

#for bamFile in $dataDir/*tophat.bam
#do
#  outFile=${bamFile/\.bam/.geneCounts}
#
#  if [ ! -f $outFile ]
#  then
#    echo Calculate read counts for $bamFile
#    scripts/rnaseq/htseq_gene_count $bamFile no $outFile &
#  fi
#done
#wait

#seq 6 9 | parallel --max-procs 4 scripts/rnaseq/pileup_count $dataDir/SRR01528{}.tophat.bam $genomeFastaFile $geneSymbolMetaFile19 $dataDir/SRR01528{}.tophat.pileupCounts

########################################
# Summarize RNA-Seq
########################################

summDir=summarization/MAQC

#mkdir -p $summDir
#rm -fv $summDir/*

#cp -v compute/MAQC/Output/SRR015286.gene.mapped $summDir/Brain1.gnumap.readsraw.txt
#cp -v compute/MAQC/Output/SRR015287.gene.mapped $summDir/Brain2.gnumap.readsraw.txt
#cp -v compute/MAQC/Output/SRR015288.gene.mapped $summDir/Brain3.gnumap.readsraw.txt
#cp -v compute/MAQC/Output/SRR015289.gene.mapped $summDir/Brain4.gnumap.readsraw.txt
#cp -v compute/MAQC/SRR015286.tophat.geneCounts $summDir/Brain1.tophatgene.readsraw.txt
#cp -v compute/MAQC/SRR015287.tophat.geneCounts $summDir/Brain2.tophatgene.readsraw.txt
#cp -v compute/MAQC/SRR015288.tophat.geneCounts $summDir/Brain3.tophatgene.readsraw.txt
#cp -v compute/MAQC/SRR015289.tophat.geneCounts $summDir/Brain4.tophatgene.readsraw.txt
#cp -v compute/MAQC/SRR015286.tophat.pileupCounts $summDir/Brain1.tophatpileup.readsraw.txt
#cp -v compute/MAQC/SRR015287.tophat.pileupCounts $summDir/Brain2.tophatpileup.readsraw.txt
#cp -v compute/MAQC/SRR015288.tophat.pileupCounts $summDir/Brain3.tophatpileup.readsraw.txt
#cp -v compute/MAQC/SRR015289.tophat.pileupCounts $summDir/Brain4.tophatpileup.readsraw.txt

#for x in gnumap tophatgene tophatpileup
#do
#  cp -v compute/MAQC/SRR015286.depth $summDir/Brain1.$x.depth.txt
#  cp -v compute/MAQC/SRR015287.depth $summDir/Brain2.$x.depth.txt
#  cp -v compute/MAQC/SRR015288.depth $summDir/Brain3.$x.depth.txt
#  cp -v compute/MAQC/SRR015289.depth $summDir/Brain4.$x.depth.txt
#done

#for f in $summDir/*tophatgene*readsraw.txt
#do
#  echo Converting to gene symbols for $f
#  python code/MergeMatrixOnRowNames.py $f library/Ensembl_GRCh37.p10_GeneSymbols.txt $tmpFile1 False
#  python code/FilterFile.py $tmpFile1 "len(x) > 2" 0 $tmpFile2
#  python code/SelectColumns.py $tmpFile2 2,1 $tmpFile1
#  python code/SummarizeDuplicateRowValues.py $tmpFile1 sum $f
#done

#scripts/transformRnaSeqSummarized "$summDir/*gnumap*" $geneSymbolMetaFile18 0.001 0.001 0.01 matrices/MAQC.gnumap.cqn2.txt
#scripts/transformRnaSeqSummarized "$summDir/*tophatgene*" $geneSymbolMetaFile19 0.001 0.001 0.01 matrices/MAQC.tophatgene.cqn2.txt
#scripts/transformRnaSeqSummarized "$summDir/*tophatpileup*" $geneSymbolMetaFile19 0.001 0.001 0.01 matrices/MAQC.tophatpileup.cqn2.txt

function matricize {
  aligner=$1
  metaFile=$2

  for dataType in readsraw reads rpkm rpkm2 probnn probln probnn2 probln2 probnb
  do
    scripts/buildMatrix "$summDir/*.$aligner.${dataType}.txt" matrices/MAQC.$aligner.${dataType}.txt
    tail -n +2 matrices/MAQC.$aligner.${dataType}.txt > $tmpFile1
    python2 code/TransformMatrixRows.py $tmpFile1 False median matrices/MAQC.$aligner.${dataType}.txt
  done

  tail -n +2 matrices/MAQC.$aligner.cqn.txt > $tmpFile1
  python2 code/TransformMatrixRows.py $tmpFile1 False median matrices/MAQC.$aligner.cqn.txt
  tail -n +2 matrices/MAQC.$aligner.cqn2.txt > $tmpFile1
  python2 code/TransformMatrixRows.py $tmpFile1 False median matrices/MAQC.$aligner.cqn2.txt
}

#matricize gnumap $geneSymbolMetaFile18
#matricize tophatgene $geneSymbolMetaFile19
#matricize tophatpileup $geneSymbolMetaFile19

source scripts/delete_temp_files
