#!/bin/bash

inFile=$1
fileSuffix=$2
cohort=$3
dataColumnIndex=$4
description=$5
probeGroup=$6
keyDescription=$7
keyProbeFile=$8
probeFile=$9
minProbesPer=${10}
summarizeFunction=${11}
outlierSamplesFile=${12}

sampleID=`basename $inFile`
sampleID=${sampleID/$fileSuffix/}
outFile=~/Pipeline/summarization/$cohort/$sampleID.$keyDescription.$probeGroup.$description.txt

if [ ! -f $outFile ]
then
  python26 ~/Pipeline/code/SummarizeData.py $sampleID $inFile $dataColumnIndex $keyProbeFile $probeFile $minProbesPer $summarizeFunction $outlierSamplesFile $outFile
fi
